/**
 * Video Summary Types Tests
 *
 * Tests for video summary type definitions and utility functions.
 * Part of the Long-Horizon Engineering Protocol - FEAT-901
 */

import { describe, it, expect } from "vitest";
import {
  type SummaryMode,
  type YouTubeVideoMetadata,
  type TranscriptSegment,
  type VideoTranscript,
  type VideoSummaryRequest,
  type VideoSummaryResponse,
  type VideoSummaryError,
  type GetVideoSummaryArgs,
  type GetVideoSummaryOutput,
  type VideoSummaryPayload,
  type VideoSummaryState,
  type CachedMetadata,
  type CachedTranscript,
  SUMMARY_MODE_TRIGGERS,
  INITIAL_VIDEO_SUMMARY_STATE,
  CACHE_TTL,
  parseIsoDuration,
  isCacheValid,
  detectSummaryMode,
} from "@/types/video-summary";

describe("Video Summary Types", () => {
  describe("SummaryMode", () => {
    it("should support default and deep modes", () => {
      const modes: SummaryMode[] = ["default", "deep"];
      expect(modes).toContain("default");
      expect(modes).toContain("deep");
    });
  });

  describe("SUMMARY_MODE_TRIGGERS", () => {
    it("should have triggers for default mode", () => {
      expect(SUMMARY_MODE_TRIGGERS.default).toContain("what are we watching");
      expect(SUMMARY_MODE_TRIGGERS.default).toContain("quick summary");
    });

    it("should have triggers for deep mode", () => {
      expect(SUMMARY_MODE_TRIGGERS.deep).toContain("analyze this video");
      expect(SUMMARY_MODE_TRIGGERS.deep).toContain("deep dive");
      expect(SUMMARY_MODE_TRIGGERS.deep).toContain("what topics are covered");
    });
  });

  describe("YouTubeVideoMetadata", () => {
    it("should have all required properties", () => {
      const metadata: YouTubeVideoMetadata = {
        videoId: "dQw4w9WgXcQ",
        title: "Never Gonna Give You Up",
        description: "The official music video for Rick Astley...",
        channelTitle: "Rick Astley",
        channelId: "UCuAXFkgsw1L7xaCfnd5JJOw",
        publishedAt: "2009-10-25T06:57:33Z",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/dQw4w9WgXcQ/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
            width: 320,
            height: 180,
          },
        },
        tags: ["Rick Astley", "Never Gonna Give You Up", "Music"],
        categoryId: "10",
        duration: "PT3M33S",
        durationSeconds: 213,
        viewCount: 1400000000,
        likeCount: 15000000,
        hasCaption: true,
      };

      expect(metadata.videoId).toBe("dQw4w9WgXcQ");
      expect(metadata.title).toBe("Never Gonna Give You Up");
      expect(metadata.channelTitle).toBe("Rick Astley");
      expect(metadata.durationSeconds).toBe(213);
      expect(metadata.hasCaption).toBe(true);
    });
  });

  describe("TranscriptSegment", () => {
    it("should have all required properties", () => {
      const segment: TranscriptSegment = {
        text: "Hello and welcome to this video",
        start: 0,
        duration: 3.5,
        end: 3.5,
      };

      expect(segment.text).toBe("Hello and welcome to this video");
      expect(segment.start).toBe(0);
      expect(segment.duration).toBe(3.5);
      expect(segment.end).toBe(3.5);
    });
  });

  describe("VideoTranscript", () => {
    it("should have all required properties", () => {
      const transcript: VideoTranscript = {
        videoId: "abc123",
        language: "en",
        isAutoGenerated: false,
        segments: [
          { text: "Hello", start: 0, duration: 1, end: 1 },
          { text: "World", start: 1, duration: 1, end: 2 },
        ],
        fullText: "Hello World",
        totalDuration: 120,
      };

      expect(transcript.videoId).toBe("abc123");
      expect(transcript.language).toBe("en");
      expect(transcript.segments).toHaveLength(2);
      expect(transcript.fullText).toBe("Hello World");
    });
  });

  describe("VideoSummaryRequest", () => {
    it("should have mode and optional videoId", () => {
      const defaultRequest: VideoSummaryRequest = {
        mode: "default",
      };

      const deepRequestWithId: VideoSummaryRequest = {
        mode: "deep",
        videoId: "abc123",
      };

      expect(defaultRequest.mode).toBe("default");
      expect(defaultRequest.videoId).toBeUndefined();
      expect(deepRequestWithId.mode).toBe("deep");
      expect(deepRequestWithId.videoId).toBe("abc123");
    });
  });

  describe("VideoSummaryResponse", () => {
    it("should have all required properties for default mode", () => {
      const response: VideoSummaryResponse = {
        mode: "default",
        usedFallback: false,
        metadata: {
          videoId: "abc123",
          title: "Test Video",
          description: "A test video",
          channelTitle: "Test Channel",
          channelId: "channel123",
          publishedAt: "2024-01-01T00:00:00Z",
          thumbnails: {},
          tags: [],
          categoryId: "22",
          duration: "PT5M",
          durationSeconds: 300,
          viewCount: 1000,
          likeCount: 100,
          hasCaption: true,
        },
        summary: "This is a 5-minute video by Test Channel about testing.",
        generatedAt: Date.now(),
        processingTimeMs: 1500,
      };

      expect(response.mode).toBe("default");
      expect(response.usedFallback).toBe(false);
      expect(response.summary).toContain("Test Channel");
    });

    it("should have extended properties for deep mode", () => {
      const response: VideoSummaryResponse = {
        mode: "deep",
        usedFallback: false,
        metadata: {
          videoId: "abc123",
          title: "Deep Dive Video",
          description: "An in-depth analysis",
          channelTitle: "Expert Channel",
          channelId: "channel456",
          publishedAt: "2024-01-01T00:00:00Z",
          thumbnails: {},
          tags: ["analysis", "deep dive"],
          categoryId: "27",
          duration: "PT30M",
          durationSeconds: 1800,
          viewCount: 50000,
          likeCount: 5000,
          hasCaption: true,
        },
        summary: "Comprehensive analysis of the topic...",
        keyPoints: [
          "First major point covered",
          "Second important topic",
          "Third key takeaway",
        ],
        topics: ["Technology", "AI", "Future Trends"],
        speakers: ["Dr. Jane Smith", "Prof. John Doe"],
        generatedAt: Date.now(),
        processingTimeMs: 5000,
      };

      expect(response.mode).toBe("deep");
      expect(response.keyPoints).toHaveLength(3);
      expect(response.topics).toContain("AI");
      expect(response.speakers).toContain("Dr. Jane Smith");
    });
  });

  describe("VideoSummaryError", () => {
    it("should support all error codes", () => {
      const errorCodes = [
        "NO_VIDEO_PLAYING",
        "VIDEO_NOT_FOUND",
        "API_ERROR",
        "TRANSCRIPT_UNAVAILABLE",
        "RATE_LIMITED",
        "UNKNOWN",
      ] as const;

      errorCodes.forEach((code) => {
        const error: VideoSummaryError = {
          code,
          message: `Error: ${code}`,
          requestedMode: "default",
        };
        expect(error.code).toBe(code);
      });
    });
  });

  describe("GetVideoSummaryArgs", () => {
    it("should have mode property", () => {
      const args: GetVideoSummaryArgs = {
        mode: "deep",
      };
      expect(args.mode).toBe("deep");
    });
  });

  describe("GetVideoSummaryOutput", () => {
    it("should represent success response", () => {
      const output: GetVideoSummaryOutput = {
        success: true,
        response: {
          mode: "default",
          usedFallback: false,
          metadata: {} as YouTubeVideoMetadata,
          summary: "Test summary",
          generatedAt: Date.now(),
          processingTimeMs: 1000,
        },
      };
      expect(output.success).toBe(true);
      expect(output.response).toBeDefined();
      expect(output.error).toBeUndefined();
    });

    it("should represent error response", () => {
      const output: GetVideoSummaryOutput = {
        success: false,
        error: {
          code: "NO_VIDEO_PLAYING",
          message: "No video is currently playing",
          requestedMode: "default",
        },
      };
      expect(output.success).toBe(false);
      expect(output.error).toBeDefined();
      expect(output.response).toBeUndefined();
    });
  });

  describe("VideoSummaryPayload", () => {
    it("should have roomId and summary", () => {
      const payload: VideoSummaryPayload = {
        roomId: "room-123",
        summary: {
          mode: "default",
          usedFallback: false,
          metadata: {} as YouTubeVideoMetadata,
          summary: "Test",
          generatedAt: Date.now(),
          processingTimeMs: 500,
        },
      };
      expect(payload.roomId).toBe("room-123");
      expect(payload.summary).toBeDefined();
    });
  });

  describe("INITIAL_VIDEO_SUMMARY_STATE", () => {
    it("should have sensible defaults", () => {
      expect(INITIAL_VIDEO_SUMMARY_STATE.loadingState).toBe("idle");
      expect(INITIAL_VIDEO_SUMMARY_STATE.lastSummary).toBeNull();
      expect(INITIAL_VIDEO_SUMMARY_STATE.error).toBeNull();
      expect(INITIAL_VIDEO_SUMMARY_STATE.lastUpdatedAt).toBeNull();
    });
  });

  describe("CACHE_TTL", () => {
    it("should have correct TTL values", () => {
      expect(CACHE_TTL.METADATA).toBe(15 * 60 * 1000); // 15 minutes
      expect(CACHE_TTL.TRANSCRIPT).toBe(60 * 60 * 1000); // 1 hour
    });
  });
});

describe("Video Summary Utility Functions", () => {
  describe("parseIsoDuration", () => {
    it("should parse hours, minutes, and seconds", () => {
      expect(parseIsoDuration("PT1H30M45S")).toBe(5445);
    });

    it("should parse minutes and seconds only", () => {
      expect(parseIsoDuration("PT5M30S")).toBe(330);
    });

    it("should parse minutes only", () => {
      expect(parseIsoDuration("PT10M")).toBe(600);
    });

    it("should parse seconds only", () => {
      expect(parseIsoDuration("PT45S")).toBe(45);
    });

    it("should return 0 for invalid format", () => {
      expect(parseIsoDuration("invalid")).toBe(0);
      expect(parseIsoDuration("")).toBe(0);
    });

    it("should parse hours only", () => {
      expect(parseIsoDuration("PT2H")).toBe(7200);
    });
  });

  describe("isCacheValid", () => {
    it("should return true for fresh cache", () => {
      const cachedAt = Date.now() - 1000; // 1 second ago
      const ttl = 60000; // 1 minute TTL
      expect(isCacheValid(cachedAt, ttl)).toBe(true);
    });

    it("should return false for expired cache", () => {
      const cachedAt = Date.now() - 120000; // 2 minutes ago
      const ttl = 60000; // 1 minute TTL
      expect(isCacheValid(cachedAt, ttl)).toBe(false);
    });

    it("should return true for cache at exactly TTL boundary", () => {
      const cachedAt = Date.now() - 59999; // Just under 1 minute
      const ttl = 60000;
      expect(isCacheValid(cachedAt, ttl)).toBe(true);
    });
  });

  describe("detectSummaryMode", () => {
    it("should detect default mode triggers", () => {
      expect(detectSummaryMode("what are we watching")).toBe("default");
      expect(detectSummaryMode("What Are We Watching?")).toBe("default");
      expect(detectSummaryMode("give me a quick summary")).toBe("default");
      expect(detectSummaryMode("who made this video")).toBe("default");
    });

    it("should detect deep mode triggers", () => {
      expect(detectSummaryMode("analyze this video")).toBe("deep");
      expect(detectSummaryMode("can you deep dive on this video")).toBe("deep");
      expect(detectSummaryMode("what topics are covered")).toBe("deep");
      expect(detectSummaryMode("give me a detailed breakdown")).toBe("deep");
      expect(detectSummaryMode("what are the main points")).toBe("deep");
    });

    it("should default to default mode for unknown queries", () => {
      expect(detectSummaryMode("hello there")).toBe("default");
      expect(detectSummaryMode("random question")).toBe("default");
    });

    it("should be case insensitive", () => {
      expect(detectSummaryMode("ANALYZE THIS VIDEO")).toBe("deep");
      expect(detectSummaryMode("WHAT ARE WE WATCHING")).toBe("default");
    });

    it("should handle queries with extra whitespace", () => {
      expect(detectSummaryMode("  analyze this video  ")).toBe("deep");
      expect(detectSummaryMode("  what are we watching  ")).toBe("default");
    });
  });
});

describe("Cache Types", () => {
  describe("CachedMetadata", () => {
    it("should have all required properties", () => {
      const cached: CachedMetadata = {
        data: {
          videoId: "abc123",
          title: "Test",
          description: "Test desc",
          channelTitle: "Channel",
          channelId: "ch123",
          publishedAt: "2024-01-01",
          thumbnails: {},
          tags: [],
          categoryId: "22",
          duration: "PT5M",
          durationSeconds: 300,
          viewCount: 1000,
          likeCount: 100,
          hasCaption: true,
        },
        cachedAt: Date.now(),
        ttl: CACHE_TTL.METADATA,
      };

      expect(cached.data.videoId).toBe("abc123");
      expect(cached.ttl).toBe(CACHE_TTL.METADATA);
    });
  });

  describe("CachedTranscript", () => {
    it("should have all required properties", () => {
      const cached: CachedTranscript = {
        data: {
          videoId: "abc123",
          language: "en",
          isAutoGenerated: true,
          segments: [],
          fullText: "",
          totalDuration: 300,
        },
        cachedAt: Date.now(),
        ttl: CACHE_TTL.TRANSCRIPT,
      };

      expect(cached.data.videoId).toBe("abc123");
      expect(cached.ttl).toBe(CACHE_TTL.TRANSCRIPT);
    });
  });
});
